export default [
  // Configurazione semplice che funziona
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-console': 'off',
      'prefer-const': 'error',
      'no-var': 'error',
    },
    ignores: [
      'dist/',
      'node_modules/',
      'build/',
      'coverage/',
      '.nyc_output/',
      '*.config.js',
      '*.config.ts',
      'vite.config.*',
      'vitest.config.*',
      'tailwind.config.*',
      'postcss.config.*',
      'prisma/migrations/',
      '*.log',
      'logs/',
      '.DS_Store',
      'Thumbs.db',
      '.vscode/',
      '.idea/',
      '*.tmp',
      '*.temp',
      'generated/',
    ],
  },
];
