-- ============================================================================
-- FIX DATABASE ISSUES
-- ============================================================================
-- Questo script corregge:
-- 1. Enum ProductType (case sensitivity)
-- 2. organization_invitations.id (manca DEFAULT)
-- ============================================================================

-- ============================================================================
-- 1. VERIFICA E CORREZIONE ENUM ProductType
-- ============================================================================

-- Prima verifica i valori esistenti
SELECT enumlabel FROM pg_enum 
WHERE enumtypid = 'ProductType'::regtype 
ORDER BY enumsortorder;

-- Se "drone" non esiste, aggiungilo (PostgreSQL 10+)
-- ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'drone';

-- Se invece i valori sono in maiuscolo, usa questo per aggiungere anche lowercase:
-- ALTER TYPE "ProductType" ADD VALUE 'drone';

-- ============================================================================
-- 2. CORREZIONE organization_invitations.id
-- ============================================================================

-- Opzione A: Usa GENERATED BY DEFAULT AS IDENTITY (PostgreSQL 10+, più moderno)
-- Prima verifica se la colonna esiste e se è già PK
DO $$
BEGIN
    -- Verifica se la colonna id esiste
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'organization_invitations' 
        AND column_name = 'id'
    ) THEN
        -- Verifica se è già identity
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'organization_invitations' 
            AND column_name = 'id'
            AND is_identity = 'YES'
        ) THEN
            -- Crea sequence se non esiste
            IF NOT EXISTS (
                SELECT 1 FROM pg_sequences 
                WHERE sequencename = 'organization_invitations_id_seq'
            ) THEN
                CREATE SEQUENCE organization_invitations_id_seq;
            END IF;
            
            -- Imposta il default usando la sequence
            ALTER TABLE organization_invitations 
            ALTER COLUMN id SET DEFAULT nextval('organization_invitations_id_seq');
            
            -- Imposta la sequence al valore max attuale +1 (per evitare conflitti)
            PERFORM setval(
                'organization_invitations_id_seq', 
                COALESCE((SELECT MAX(id) FROM organization_invitations), 0) + 1
            );
            
            -- Rendi id PK se non lo è già
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints 
                WHERE table_name = 'organization_invitations' 
                AND constraint_type = 'PRIMARY KEY'
            ) THEN
                ALTER TABLE organization_invitations ADD PRIMARY KEY (id);
            END IF;
            
            RAISE NOTICE '✅ organization_invitations.id configurato correttamente';
        ELSE
            RAISE NOTICE 'ℹ️ organization_invitations.id è già configurato come IDENTITY';
        END IF;
    ELSE
        RAISE NOTICE '⚠️ Colonna organization_invitations.id non trovata';
    END IF;
END $$;

-- ============================================================================
-- VERIFICA FINALE
-- ============================================================================

-- Verifica enum ProductType
SELECT 'ProductType enum values:' as info;
SELECT enumlabel FROM pg_enum 
WHERE enumtypid = 'ProductType'::regtype 
ORDER BY enumsortorder;

-- Verifica organization_invitations
SELECT 'organization_invitations.id configuration:' as info;
SELECT 
    column_name,
    data_type,
    is_nullable,
    column_default,
    is_identity
FROM information_schema.columns 
WHERE table_name = 'organization_invitations' 
AND column_name = 'id';

